{
 "title": "Docker Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "environment",
    "query": {
     "query": "label_values(cadvisor_version_info, env)"
    }
   },
   {
    "name": "cadvisor",
    "label": "Cadvisor",
    "query": {
     "query": "label_values(cadvisor_version_info{env=~\"$environment\",job=~\"$jobcadvisor\"}, instance)"
    }
   },
   {
    "name": "jobcadvisor",
    "label": "JobCadvisor",
    "query": {
     "query": "label_values(cadvisor_version_info, job)"
    }
   },
   {
    "name": "node_exporter",
    "query": {
     "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\",job=~\"$jobnode\",nodename=~\"$hostname\"},instance)"
    }
   },
   {
    "name": "origin_prometheus",
    "query": {
     "query": "label_values(origin_prometheus)"
    }
   },
   {
    "name": "jobnode",
    "label": "JobNode",
    "query": {
     "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\"}, job)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "hostname",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\",job=~\"$jobnode\"}, nodename)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Containers Paused",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers{state=\"paused\"}"
    }
   ]
  },
  {
   "title": "Containers running",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers{state=\"running\"}"
    }
   ]
  },
  {
   "title": "Containers Stopped",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers{state=\"stopped\"}"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{id=~\"/docker/.*\",instance=~\"$cadvisor\"}[5m]))"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{name!=\"\",instance=~\"$cadvisor\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name!=\"\",instance=~\"$cadvisor\"}[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\",instance=~\"$cadvisor\"}[5m])) by (name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "RSS Memory Usage per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{name!=\"\",instance=~\"$cadvisor\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Used Memory per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name!=\"\",instance=~\"$cadvisor\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Available Memory per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_spec_memory_limit_bytes{name!=\"\",instance=~\"$cadvisor\"}-container_memory_usage_bytes{name!=\"\",instance=~\"$cadvisor\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Limit Memory per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_spec_memory_limit_bytes{name!=\"\",instance=~\"$cadvisor\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory usage per container",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{name!=\"\",instance=~\"$cadvisor\"}) by (name)"
    },
    {
     "expr": "max(container_memory_max_usage_bytes{name!=\"\",instance=~\"$cadvisor\"}-container_memory_usage_bytes{name!=\"\",instance=~\"$cadvisor\"})by (name)"
    },
    {
     "expr": "max(container_memory_max_usage_bytes{name!=\"\",instance=~\"$node\"}) by (name)"
    }
   ]
  }
 ]
}