{
 "title": "MongoDB",
 "description": "Note for a official Grafana MongoDB plugin, please view:\nhttps://grafana.com/grafana/plugins/grafana-mongodb-datasource\n\nThis is a MongoDB Prometheus Exporter Dashboard. \nWorks well with https://github.com/dcu/mongodb_exporter\n\nIf you have the node_exporter running on the mongo instance, you will also get some useful alert panels related to disk io and cpu.",
 "tags": [ "prometheus" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "env", "label": "env", "query": "mongodb_exporter:9216" },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "node_exporter",
    "query": {
     "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\",job=~\"$jobnode\",nodename=~\"$hostname\"},instance)"
    }
   },
   {
    "name": "jobnode",
    "label": "JobNode",
    "query": {
     "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\"}, job)"
    }
   },
   {
    "name": "hostname",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\",job=~\"$jobnode\"}, nodename)"
    }
   },
   {
    "name": "origin_prometheus",
    "label": "Origin_prom",
    "query": {
     "query": "label_values(origin_prometheus)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Query Metrics for $env", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "env" },
  {
   "title": "Query Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_total{instance=\"$env\"}[$interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Document Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_document_total{instance=\"$env\"}[$interval])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Document Query Executor",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_query_executor_total{instance=~\"$env\"}[$interval])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_network_bytes_total{instance=\"$env\"}[$interval])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Health metrics for $env",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "repeat": "env",
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mongodb_instance_uptime_seconds{instance=~\"$env\"}"
      }
     ]
    },
    {
     "title": "Available Connections",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mongodb_connections{instance=~\"$env\",state=\"available\"}"
      }
     ]
    },
    {
     "title": "Open Connections",
     "type": "stat",
     "gridPos": { "h": 4, "w": 16, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mongodb_connections{instance=~\"$env\",state=\"current\"}"
      }
     ]
    }
   ]
  },
  { "title": "Resource Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Oplog Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_repl_oplog_insert_bytes_total{instance=~\"$env\"}[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "decmbytes", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "mongodb_memory{instance=~\"$env\",type=~\"resident|virtual\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Dashboard Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Reads Completed",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_reads_completed_total{instance=\"$node_exporter\"}[5m])",
       "legendFormat": "{{device}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Disk Writes Completed",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_writes_completed_total{instance=\"$node_exporter\"}[2m])",
       "legendFormat": "{{device}} - {{instance}}"
      }
     ]
    }
   ]
  }
 ]
}