{
 "title": "Overview",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "query": {
     "query": "label_values(cadvisor_version_info, env)"
    }
   },
   {
    "name": "cadvisor",
    "label": "Cadvisor",
    "query": {
     "query": "label_values(cadvisor_version_info{env=~\"$environment\",job=~\"$jobcadvisor\"}, instance)"
    }
   },
   {
    "name": "node_exporter",
    "query": {
     "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\",job=~\"$jobnode\",nodename=~\"$hostname\"},instance)"
    }
   },
   {
    "name": "origin_prometheus",
    "query": {
     "query": "label_values(origin_prometheus)"
    }
   },
   {
    "name": "jobnode",
    "label": "JobNode",
    "query": {
     "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\"}, job)"
    }
   },
   {
    "name": "jobcadvisor",
    "label": "JobCadvisor",
    "query": {
     "query": "label_values(cadvisor_version_info, job)"
    }
   },
   {
    "name": "hostname",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\",job=~\"$jobnode\"}, nodename)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk space /",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "min((node_filesystem_size_bytes{fstype=~\"xfs|ext4\",instance=~\"$node_exporter\"} - node_filesystem_free_bytes{fstype=~\"xfs|ext4\",instance=~\"$node_exporter\"} )/ node_filesystem_size_bytes{fstype=~\"xfs|ext4\",instance=~\"$node_exporter\"})",
       "legendFormat": "/"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "((node_memory_MemTotal_bytes{instance=~\"$node_exporter\"} - node_memory_MemAvailable_bytes{instance=~\"$node_exporter\"}) / node_memory_MemTotal_bytes{instance=~\"$node_exporter\"}) * 100"
      }
     ]
    },
    {
     "title": "Total RAM",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$node_exporter\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - node_boot_time_seconds{instance=~\"$node_exporter\"}"
      }
     ]
    },
    {
     "title": "CPU Cores",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(node_cpu_seconds_total{instance=~\"$node_exporter\", mode='system'})"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(rate(container_last_seen{id=~\"/docker/.*\",instance=~\"$cadvisor\"}[5m]))"
      }
     ]
    },
    {
     "title": "Memory usage per container",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "targets": [
      {
       "expr": "max(container_memory_usage_bytes{name!=\"\",instance=~\"$cadvisor\"}) by (name)"
      },
      {
       "expr": "max(container_memory_max_usage_bytes{name!=\"\",instance=~\"$cadvisor\"}-container_memory_usage_bytes{name!=\"\",instance=~\"$cadvisor\"})by (name)"
      },
      {
       "expr": "max(container_memory_max_usage_bytes{name!=\"\",instance=~\"$node\"}) by (name)"
      }
     ]
    }
   ]
  },
  {
   "title": "VerneMQ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connected Clients",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "(socket_open - socket_close)" }
     ]
    },
    {
     "title": "Queues Processes",
     "type": "stat",
     "description": "This is the current total of living queues (started queue processes). These queues might be in an online or an offline state (ie. belong to an online or offline client).",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "queue_processes" }
     ]
    },
    {
     "title": "VerneMQ Node Uptime",
     "type": "stat",
     "description": "VerneMQ Broker Uptime",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "system_wallclock" }
     ]
    },
    {
     "title": "Erlang VM Utilization",
     "type": "gauge",
     "description": "VerneMQ Broker average Erlang Scheduler utilization.",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "system_utilization" }
     ]
    }
   ]
  }
 ]
}