global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: prometheus
    metrics_path: /metrics
    honor_labels: false
    honor_timestamps: true
    scheme: http
    static_configs:
      - targets: ['localhost:9090']

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: node_exporter
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: docker
    static_configs:
      - targets: ['172.17.0.1:9323'] # 172.17.0.1 docker network interface default port "docker0"

  - job_name: vernemq
    static_configs:
      - targets: ['iotagent-mqtt:8888']

  - job_name: kafka_exporter
    static_configs:
      - targets: ['kafka_exporter:9308']

  - job_name: apigw
    static_configs:
      - targets: ['apigw:8001']