FORMAT: 1A

# Middleware APIs

Endpoints to manage connected devices

<!-- include(./Orchestrator.apib) -->
<!-- include(./STH.apib) -->
<!-- include(DeviceManager/Devices.apib) -->
<!-- include(DeviceManager/Templates.apib) -->
<!-- include(Orion/orion-v1.apib) -->
<!-- include(Orion/orion-v2/fiware-ngsiv2-rc-2016_05_31.apib) -->
<!-- include(Orion/orion-v2/fiware-ngsiv2-rc-2016_10_31.apib) -->
<!-- include(Orion/orion-v2/fiware-ngsiv2-reference.apib) -->
<!-- include(Orion/orion-v2/fiware-ngsiv2-reference.errata) -->
<!-- include(Orion/orion-v2/fiware-ngsiv2-cookbook.apib) -->
<!-- include(Orion/orion-v2/fiware-ngsiv2-cookbook-rc-2016_05_31.apib) -->

