# Group Flow

## Flows [/flows/v1/flow]
### Get the current configured flows [GET]
Returns all currently configured flows
+ Request
  + Headers:
    Authorization: Bearer JWT
+ Response 200 (application/json)
  + Body
    [
      {
        "id" : "8476897",
        "enabled" : "true",
        "created" : "1498482705349",
        "updated" : "1498482705349",
        "service" : "admin",
        "servicePath" : "/",
        "perseoRules" : {
          "headers" {
            "service": "admin",
            "servicePath" : "/"
          },
          "rules" : [
            "rule_939851_1",
            "rule_939851_2"
          ]
        },
        "flow" : {
          // Flow description as in input
        }
      }
    ]
+ Response 500
  {
    "msg" : "failed to retrieve data"
  }


### Configure a new flow [POST]
Adds a new flow.
+ Request (application/json)
  + Headers:
    Authorization: Bearer JWT
  + Body
    {
      "id" : "8476897",
      "service" : "admin",
      "servicePath" : "/",
      "flow" : {
        // Flow description directly from mashup
      }
    }
+ Response 200
  {
    "msg" : "flow created",
    "flow" : {
      "id" : "8476897",
      "enabled" : "true",
      "created" : "1498482705349",
      "updated" : "1498482705349",
      "service" : "admin",
      "servicePath" : "/",
      "perseoRules" : {
        "headers" {
          "service": "admin",
          "servicePath" : "/"
        },
        "rules" : [
          "rule_939851_1",
          "rule_939851_2"
        ]
      },
      "flow" : {
        // Flow description as in input
      }
    }
  }
+ Response 400
  {
    "msg" : "missing flow data"
  }
+ Response 500
  {
    "msg" : "failed to insert data"
  }

### Removes all flows [DELETE]
Removes all flows and their configurations.
+ Request (application/json)
  + Headers:
    Authorization: Bearer JWT

+ Response 200
  {
    "msg" : "all flows removed"
  }

## Flows [/flows/v1/flow/{id}]
  + Parameters
    + id The identifier associated to the flow
### Get the current configured flows [GET]
Returns the configuration of a particular flow
+ Request
  + Headers:
    Authorization: Bearer JWT
+ Response 200 (application/json)
  + Body
    {
      "msg" : "ok",
      "flow" : {
        "id" : "8476897",
        "enabled" : "true",
        "created" : "1498482705349",
        "updated" : "1498482705349",
        "service" : "admin",
        "servicePath" : "/",
        "perseoRules" : {
          "headers" {
            "service": "admin",
            "servicePath" : "/"
          },
          "rules" : [
            "rule_939851_1",
            "rule_939851_2"
          ]
        },
        "flow" : {
          // Flow description as in input
        }
      }
    }
+ Response 500
  {
    "msg" : "failed to retrieve data"
  }


### Reconfigure a specific flow [PUT]
Reconfigure a particular flow - the old config will be removed and the new one will be deployed.
+ Request (application/json)
  + Headers:
    Authorization: Bearer JWT
  + Body
    {
      "id" : "8476897",
      "service" : "admin",
      "servicePath" : "/",
      "flow" : {
        // Flow description directly from mashup
      }
    }
+ Response 200
  {
    "msg" : "flow updated",
    "flow" : {
      "id" : "8476897",
      "enabled" : "true",
      "created" : "1498482705349",
      "updated" : "1498482705349",
      "service" : "admin",
      "servicePath" : "/",
      "perseoRules" : {
        "headers" {
          "service": "admin",
          "servicePath" : "/"
        },
        "rules" : [
          "rule_939851_1",
          "rule_939851_2"
        ]
      },
      "flow" : {
        // Flow description as in input
      }
    }
  }
+ Response 400
  {
    "msg" : "missing flow data"
  }
+ Response 404
  {
    "msg" : "given flow is unknown"
  }
+ Response 500
  {
    "msg" : "failed to remove flow"
  }
+ Response 500
  {
    "msg" : "failed to insert data"
  }

### Remove the flow [DELETE]
Removes the flow and its configuration.
+ Request (application/json)
  + Headers:
    Authorization: Bearer JWT

+ Response 200
  {
    "msg" : "flow removed",
    "id" : "8476897"
  }

+ Response 500
  {
    "msg" : "failed to remove flow"
  }

+ Response 404
  {
    "msg" : "given flow is unknown"
  }
